// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package searchsvc

import (
	"github.com/krazybee/internals/config"
	"github.com/krazybee/internals/config/jsonconfig"
	"github.com/krazybee/internals/dbaccess"
	"github.com/krazybee/internals/dbaccess/mysql"
)

// Injectors from wire.go:

func initContainer(path string) (*Container, error) {
	provider, err := ResolveConfigProvider(path)
	if err != nil {
		return nil, err
	}
	dbaccessProvider, err := ResolveDBProvider(provider)
	if err != nil {
		return nil, err
	}
	container := &Container{
		ConfigProvider: provider,
		DBProvider:     dbaccessProvider,
	}
	return container, nil
}

// wire.go:

func ResolveConfigProvider(path string) (config.Provider, error) {
	provider, err := jsonconfig.NewJsonConfigProvider(string(path))
	if err != nil {
		return nil, err
	}
	err = provider.Initialize()
	return provider, nil
}

func ResolveDBProvider(config2 config.Provider) (dbaccess.Provider, error) {
	provider, err := mysql.NewDBProvider(config2)
	if err != nil {
		return nil, err
	}
	return provider, nil
}
